all: BiggestUnInt.exe HelloWorld.exe SimpleClass.exe

BiggestUnInt.exe:BiggestUnInt.cc
	g++ -o BiggestUnInt.exe BiggestUnInt.cc

HelloWorld.exe:HelloWorld.cpp
	g++ -o HelloWorld.exe HelloWorld.cpp

SimpleClass.exe:SimpleClass.cc
	g++ -o SimpleClass.exe SimpleClass.cc




    
